[build]
  # La carpeta de salida de tu build (donde se generar치n los archivos de producci칩n).
  publish = "dist"
  # El comando que Netlify debe ejecutar para construir el proyecto.
  command = "npm run build"

# Opcional: Configuraci칩n del contexto de despliegue para producci칩n
[context.production]
  environment = { NODE_ENV = "production" }

# Si necesitas redireccionar rutas para manejar rutas en una SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
